# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aniru/Desktop/ELD/Lab7hw/lab7hw.srcs/sources_1/ip/FP_mul/FP_mul.xci
# IP: The module: 'FP_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aniru/Desktop/ELD/Lab7hw/lab7hw.srcs/sources_1/ip/FP_mul/FP_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_mul'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/aniru/Desktop/ELD/Lab7hw/lab7hw.srcs/sources_1/ip/FP_mul/FP_mul.xci
# IP: The module: 'FP_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aniru/Desktop/ELD/Lab7hw/lab7hw.srcs/sources_1/ip/FP_mul/FP_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_mul'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
