webtalk_init -webtalk_dir C:/Users/aniru/Desktop/ELD/lab7cw/lab7cw.sim/sim_1/behav/xsim/xsim.dir/FFT_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 15 10:52:47 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211433259_1777510721_210765779_928" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c2b54de4-d1f3-406d-8b17-b37a7d3cb334" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2f812ab0dc3b456094852ffdd232e55a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "47720445 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14604_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3696732125 -regid "211433259_1777510721_210765779_928" -xml C:/Users/aniru/Desktop/ELD/lab7cw/lab7cw.sim/sim_1/behav/xsim/xsim.dir/FFT_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/aniru/Desktop/ELD/lab7cw/lab7cw.sim/sim_1/behav/xsim/xsim.dir/FFT_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/aniru/Desktop/ELD/lab7cw/lab7cw.sim/sim_1/behav/xsim/xsim.dir/FFT_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
