# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aniru/Desktop/ELD/lab6hw/lab6hw.srcs/sources_1/ip/FP_root/FP_root.xci
# IP: The module: 'FP_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aniru/Desktop/ELD/lab6hw/lab6hw.srcs/sources_1/ip/FP_root/FP_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_root'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/aniru/Desktop/ELD/lab6hw/lab6hw.srcs/sources_1/ip/FP_root/FP_root.xci
# IP: The module: 'FP_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aniru/Desktop/ELD/lab6hw/lab6hw.srcs/sources_1/ip/FP_root/FP_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_root'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
